image: Visual Studio 2019

branches:
  except:
  - experimental

init:
  - git config --global core.autocrlf true

version: 1.0.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - dotnet --info
  - dotnet restore
  - dotnet tool install --global codecov.tool

build_script:
  - dotnet build src\Aqua.AccessControl
  - dotnet build test\Aqua.AccessControl.Tests
  - dotnet build test\Aqua.AccessControl.Tests.SQLite.EF6
  - dotnet build test\Aqua.AccessControl.Tests.SQLite.EFCore
  - dotnet build test\Aqua.AccessControl.Tests.SqlServer.EFCore

test_script:
  - dotnet test test\Aqua.AccessControl.Tests
  - dotnet test test\Aqua.AccessControl.Tests.SQLite.EF6
  - dotnet test test\Aqua.AccessControl.Tests.SQLite.EFCore

after_test:
  - dotnet test test\Aqua.AccessControl.Tests               -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory .\TestResults
  - dotnet test test\Aqua.AccessControl.Tests.SQLite.EFCore -f netcoreapp3.0 --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory .\TestResults
  - codecov -f **\coverage.cobertura.xml

build:
  verbosity: normal